In [1]:
import numpy as np;

In [2]:
mylist = [1,2,3]
x = np.array(mylist)

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [6]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
m.shape

(2, 3)

In [8]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [19]:
x = np.linspace(0, 4, 9)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [20]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [22]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [25]:
np.zeros((2, 3))
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [30]:
a.argmax()

4

In [31]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [32]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [34]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
r[-1, ::2]

array([30, 32, 34])

In [37]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [38]:
r[r>30]

array([31, 32, 33, 34, 35])

In [40]:
x = r[:3, :3]
x

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [41]:
x[0, 1] = 0
x

array([[ 0,  0,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [42]:
r

array([[ 0,  0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
prim_array = [1,1,1,1]
slice_array = prim_array[:]
slice_array[0] = 0
print(prim_array)
print(slice_array)

[1, 1, 1, 1]
[0, 1, 1, 1]
